//! Typed node references (`Key<T>`), their dependency tuples (`Deps`) and the
//! per-run slot table the engine will fill.
//!
//! A key is a plain `Copy` value: it can be stored in a struct, captured by a
//! body closure and passed to a function that builds a child plan. It is
//! **unbranded** — the type system does not stop a key of plan A from being
//! named in plan B. That mistake is caught at `build` by
//! [`Rule::ForeignKey`](crate::Rule::ForeignKey), before any effect, and the
//! contract says so plainly (`AdversarialReview.md` F-B1).
//!
//! What the compiler *does* enforce: a key exists only after its node's
//! terminal method ran, so a dependency on an undeclared node and a dependency
//! cycle are both unwritable (`E0425`), and a key carries its value type, so a
//! body whose parameters disagree with its `needs` does not compile (`E0631`).

use std::marker::PhantomData;
use std::sync::Arc;

/// A node reference with the type erased: which plan, and which node in it.
///
/// Declaration order is `idx` order: node 0 is the first node declared. Report
/// ordering (F4) and `PlanView` node order are both `idx` order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RawKey {
    /// Identity of the plan (or plan builder) that created the node.
    pub plan: u64,
    /// Declaration index of the node within that plan.
    pub idx: u32,
}

/// A typed reference to a declared node, returned by the node's terminal
/// method. `Copy + Send + Sync` for every `T`, including unsized `T` such as
/// `dyn Trait`.
///
/// Dependents that `needs` this key receive `Arc<T>`.
pub struct Key<T: ?Sized> {
    raw: RawKey,
    _t: PhantomData<fn() -> Arc<T>>,
}

impl<T: ?Sized> Key<T> {
    pub(crate) fn from_raw(raw: RawKey) -> Self {
        Key {
            raw,
            _t: PhantomData,
        }
    }

    /// The untyped node reference behind this key.
    pub fn raw(&self) -> RawKey {
        self.raw
    }
}

impl<T: ?Sized> Clone for Key<T> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<T: ?Sized> Copy for Key<T> {}
impl<T: ?Sized> PartialEq for Key<T> {
    fn eq(&self, other: &Self) -> bool {
        self.raw == other.raw
    }
}
impl<T: ?Sized> Eq for Key<T> {}
impl<T: ?Sized> std::fmt::Debug for Key<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Key({}/{})", self.raw.plan, self.raw.idx)
    }
}

/// What a node depends on: `()`, one `Key<A>`, or a tuple of keys up to eight.
///
/// `Out` is what the node's body receives: `()`, `Arc<A>`, or the matching
/// tuple of `Arc`s. The impls for tuples are generated by a private
/// `macro_rules!`; no public macro exists.
pub trait Deps: Copy + Send + Sync + 'static {
    /// The value shape the body receives.
    type Out: Send + 'static;

    /// The referenced nodes, in the order they were written.
    fn raw_keys(&self) -> Vec<RawKey>;

    /// Read the dependency values out of a run's slot table.
    ///
    /// `None` means a slot was empty, which is an engine error rather than an
    /// author error: a node is started only once every need is `Ready`.
    fn fetch(&self, slots: &Slots) -> Option<Self::Out>;
}

impl Deps for () {
    type Out = ();
    fn raw_keys(&self) -> Vec<RawKey> {
        Vec::new()
    }
    fn fetch(&self, _: &Slots) -> Option<()> {
        Some(())
    }
}

impl<A: ?Sized + Send + Sync + 'static> Deps for Key<A> {
    type Out = Arc<A>;
    fn raw_keys(&self) -> Vec<RawKey> {
        vec![self.raw]
    }
    fn fetch(&self, s: &Slots) -> Option<Arc<A>> {
        s.get::<A>(self.raw)
    }
}

macro_rules! tuple_deps {
    ($($name:ident $idx:tt),+) => {
        impl<$($name: ?Sized + Send + Sync + 'static),+> Deps for ($(Key<$name>,)+) {
            type Out = ($(Arc<$name>,)+);
            fn raw_keys(&self) -> Vec<RawKey> { vec![$(self.$idx.raw),+] }
            fn fetch(&self, s: &Slots) -> Option<Self::Out> {
                Some(($(s.get::<$name>(self.$idx.raw)?,)+))
            }
        }
    };
}
tuple_deps!(A 0);
tuple_deps!(A 0, B 1);
tuple_deps!(A 0, B 1, C 2);
tuple_deps!(A 0, B 1, C 2, D 3);
tuple_deps!(A 0, B 1, C 2, D 3, E 4);
tuple_deps!(A 0, B 1, C 2, D 3, E 4, F 5);
tuple_deps!(A 0, B 1, C 2, D 3, E 4, F 5, G 6);
tuple_deps!(A 0, B 1, C 2, D 3, E 4, F 5, G 6, H 7);

/// A run's outputs: one erased `Arc<T>` per node.
///
/// The stored value is always an `Arc<T>`, which is `Sized + 'static` even when
/// `T` is not, so `dyn Trait` outputs travel through `Box<dyn Any>` unharmed.
/// Slots are per run (INV-13): two runs of one plan share none.
pub struct Slots {
    inner: Vec<Option<Box<dyn std::any::Any + Send + Sync>>>,
}

impl Slots {
    /// An empty table for a plan with `n` nodes.
    pub fn new(n: usize) -> Self {
        Slots {
            inner: (0..n).map(|_| None).collect(),
        }
    }

    /// Store a node's output.
    pub fn set<T: ?Sized + Send + Sync + 'static>(&mut self, key: RawKey, v: Arc<T>) {
        self.set_erased(key, Box::new(v));
    }

    /// Store a node's output that the seam already erased (what `Cx::hold`
    /// registered).
    pub fn set_erased(&mut self, key: RawKey, v: Box<dyn std::any::Any + Send + Sync>) {
        self.inner[key.idx as usize] = Some(v);
    }

    /// Read a node's output, or `None` if the slot is empty or holds another type.
    pub fn get<T: ?Sized + Send + Sync + 'static>(&self, key: RawKey) -> Option<Arc<T>> {
        self.inner[key.idx as usize]
            .as_ref()
            .and_then(|b| b.downcast_ref::<Arc<T>>())
            .cloned()
    }

    /// Number of slots.
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// Whether the table has no slots at all.
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
}
